CREATE TABLE exercise_videos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  exercise_id UUID NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  provider TEXT NOT NULL DEFAULT 'evolua',
  language TEXT NOT NULL DEFAULT 'pt-BR',
  is_primary BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_exercise_videos_exercise
  ON exercise_videos(exercise_id, is_primary DESC);

INSERT INTO exercises (
  slug, name, primary_muscle, secondary_muscles, movement_pattern, equipment,
  instructions, common_errors, safety_notes, active
) VALUES
  ('agachamento-goblet', 'Agachamento Goblet', 'quadríceps', ARRAY['glúteos','core'], 'agachamento', ARRAY['halteres'],
   'Mantenha o peso próximo ao peito, pés firmes e desça de forma controlada dentro de uma amplitude confortável.',
   'Perder o alinhamento dos joelhos, acelerar a descida e arredondar excessivamente a coluna.',
   'A amplitude deve respeitar mobilidade e ausência de dor articular.', true),
  ('leg-press-45', 'Leg Press 45°', 'quadríceps', ARRAY['glúteos','posteriores'], 'flexao-profunda-joelho', ARRAY['máquinas'],
   'Apoie toda a região lombar, mantenha os pés estáveis e controle a descida sem retirar o quadril do encosto.',
   'Descer além da mobilidade disponível, travar os joelhos e perder o apoio lombar.',
   'Reduzir amplitude diante de desconforto em joelhos, quadril ou lombar.', true),
  ('hip-thrust', 'Hip Thrust', 'glúteos', ARRAY['posteriores','core'], 'extensao-quadril', ARRAY['barras'],
   'Apoie a parte superior das costas, mantenha o abdômen ativo e estenda o quadril sem hiperestender a lombar.',
   'Impulsionar pela lombar, afastar os pés demais e perder controle na descida.',
   'Interromper se houver dor lombar ou pélvica fora do esforço muscular esperado.', true),
  ('mesa-flexora', 'Mesa Flexora', 'posteriores', ARRAY['panturrilhas'], 'flexao-joelho-controlada', ARRAY['máquinas'],
   'Ajuste o equipamento ao corpo e flexione os joelhos de forma controlada, sem retirar o quadril do apoio.',
   'Usar impulso, elevar o quadril e encurtar a amplitude sem necessidade.',
   'Evitar insistir em amplitudes que provoquem dor no joelho.', true),
  ('panturrilha-em-pe', 'Elevação de Panturrilha em Pé', 'panturrilhas', ARRAY[]::text[], 'flexao-plantar', ARRAY['máquinas','peso corporal'],
   'Eleve os calcanhares com controle, faça uma breve pausa no topo e retorne lentamente.',
   'Quicar no final da amplitude e deslocar o peso para as bordas dos pés.',
   'Usar apoio estável quando houver dificuldade de equilíbrio.', true),
  ('supino-halteres', 'Supino com Halteres', 'peitoral', ARRAY['tríceps','ombros'], 'empurrar-horizontal', ARRAY['halteres'],
   'Mantenha as escápulas apoiadas, punhos neutros e desça os halteres com controle.',
   'Abrir excessivamente os cotovelos, perder a posição das escápulas e usar carga sem controle.',
   'Reduzir amplitude se houver desconforto no ombro.', true),
  ('remada-baixa', 'Remada Baixa no Cabo', 'costas', ARRAY['bíceps','deltoide posterior'], 'puxar-horizontal', ARRAY['cabo'],
   'Mantenha o tronco estável e puxe o cabo conduzindo os cotovelos para trás sem elevar os ombros.',
   'Usar balanço do tronco e transformar o movimento em encolhimento dos ombros.',
   'Evitar compensações da coluna para aumentar artificialmente a carga.', true),
  ('puxada-frontal', 'Puxada Frontal', 'costas', ARRAY['bíceps'], 'puxar-vertical', ARRAY['máquinas','cabo'],
   'Puxe a barra em direção à parte superior do peito, mantendo o tronco estável e o pescoço neutro.',
   'Puxar atrás da cabeça, balançar o tronco e perder controle da volta.',
   'Movimentos dolorosos no ombro devem ser substituídos.', true),
  ('desenvolvimento-halteres', 'Desenvolvimento com Halteres', 'ombros', ARRAY['tríceps'], 'press-acima-cabeca', ARRAY['halteres'],
   'Mantenha o tronco estável e eleve os halteres acima da cabeça sem compensar com a lombar.',
   'Hiperestender a lombar, elevar os ombros e usar amplitude desconfortável.',
   'Evitar quando houver dor no ombro ou restrição para movimentos acima da cabeça.', true),
  ('rosca-alternada', 'Rosca Alternada', 'bíceps', ARRAY['antebraços'], 'flexao-cotovelo', ARRAY['halteres'],
   'Mantenha os cotovelos próximos ao tronco e flexione o braço sem embalo.',
   'Balançar o tronco e projetar os cotovelos para a frente.',
   'Carga deve permitir controle completo do movimento.', true),
  ('triceps-corda', 'Tríceps na Corda', 'tríceps', ARRAY[]::text[], 'extensao-cotovelo', ARRAY['cabo'],
   'Mantenha os cotovelos estáveis ao lado do corpo e estenda os braços com controle.',
   'Mover os ombros para gerar impulso e abrir excessivamente os cotovelos.',
   'Ajustar carga e amplitude diante de desconforto no cotovelo.', true),
  ('dead-bug', 'Dead Bug', 'core', ARRAY['flexores do quadril'], 'estabilidade-core', ARRAY['peso corporal'],
   'Mantenha a lombar em posição confortável e mova braços e pernas lentamente sem perder controle do tronco.',
   'Arquear a lombar e acelerar o movimento.',
   'Reduzir a alavanca se não for possível manter controle.', true),
  ('bird-dog', 'Bird Dog', 'core', ARRAY['glúteos','costas'], 'estabilidade-core', ARRAY['peso corporal'],
   'Em quatro apoios, estenda braço e perna opostos mantendo a pelve estável.',
   'Girar o quadril e hiperestender a lombar.',
   'Executar em amplitude confortável e sem dor.', true),
  ('bicicleta-ergometrica', 'Bicicleta Ergométrica', 'cardiorrespiratório', ARRAY['quadríceps','glúteos'], 'cardio-baixo-impacto', ARRAY['bicicleta'],
   'Ajuste o banco, mantenha cadência confortável e esforço compatível com a sessão proposta.',
   'Banco muito baixo, carga excessiva e perda de controle da cadência.',
   'Interromper diante de dor, tontura, falta de ar incomum ou sintomas novos.', true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  movement_pattern = EXCLUDED.movement_pattern,
  equipment = EXCLUDED.equipment,
  instructions = EXCLUDED.instructions,
  common_errors = EXCLUDED.common_errors,
  safety_notes = EXCLUDED.safety_notes,
  active = EXCLUDED.active;
