export type ExercisePoseFamily =
  | 'squat'
  | 'press'
  | 'pull'
  | 'hinge'
  | 'curl'
  | 'pushdown'
  | 'core-supine'
  | 'quadruped'
  | 'calf'
  | 'bike'
  | 'pushup'
  | 'jumping-jack'
  | 'dip'
  | 'high-knees'
  | 'tai-chi'
  | 'walk'
  | 'lunge';

export type ExerciseGuidancePhase = {
  title: string;
  cue: string;
  breathing: string;
};

export type ExerciseGuidance = {
  title: string;
  pose: ExercisePoseFamily;
  beginnerTip: string;
  commonErrors: string;
  phases: [ExerciseGuidancePhase, ExerciseGuidancePhase, ExerciseGuidancePhase, ExerciseGuidancePhase];
};

const phase = (title: string, cue: string, breathing: string): ExerciseGuidancePhase => ({ title, cue, breathing });
const four = (
  title: string,
  pose: ExercisePoseFamily,
  beginnerTip: string,
  commonErrors: string,
  p1: ExerciseGuidancePhase,
  p2: ExerciseGuidancePhase,
  p3: ExerciseGuidancePhase,
  p4: ExerciseGuidancePhase,
): ExerciseGuidance => ({ title, pose, beginnerTip, commonErrors, phases: [p1, p2, p3, p4] });

const catalog: Record<string, ExerciseGuidance> = {
  'agachamento goblet': four('Agachamento Goblet', 'squat', 'Comece sem carga ou com halter leve até dominar o movimento.', 'Joelhos caindo para dentro, coluna arredondada e descida rápida.', phase('Posição inicial', 'Pés firmes, halter junto ao peito e abdômen ativo.', 'Inspire antes de descer.'), phase('Descida', 'Leve o quadril para baixo e para trás mantendo os joelhos alinhados.', 'Mantenha o ar e o tronco firme.'), phase('Ponto inferior', 'Pare na amplitude confortável sem perder postura.', 'Não prenda o ar por tempo excessivo.'), phase('Subida', 'Empurre o chão e retorne mantendo peito e joelhos alinhados.', 'Expire durante a subida.')),
  'agachamento para cadeira': four('Agachamento para cadeira', 'squat', 'Use uma cadeira firme e comece com amplitude curta.', 'Sentar despencando, joelhos para dentro e usar impulso.', phase('Posição inicial', 'Fique à frente da cadeira, pés estáveis e braços confortáveis.', 'Inspire.'), phase('Descida', 'Leve o quadril para trás até aproximar da cadeira.', 'Controle a respiração.'), phase('Contato', 'Toque a cadeira suavemente sem relaxar completamente.', 'Mantenha o tronco firme.'), phase('Subida', 'Empurre o chão e fique em pé sem balanço.', 'Expire ao subir.')),
  'leg press 45°': four('Leg Press 45°', 'squat', 'Comece com carga leve e ajuste banco/plataforma antes da primeira repetição.', 'Quadril saindo do encosto, joelhos travados e amplitude excessiva.', phase('Posição inicial', 'Lombar apoiada, pés inteiros na plataforma e joelhos destravados.', 'Inspire.'), phase('Descida', 'Flexione os joelhos devagar sem perder o apoio da lombar.', 'Mantenha o tronco estável.'), phase('Ponto inferior', 'Pare antes de o quadril enrolar ou surgir desconforto.', 'Respiração controlada.'), phase('Empurrar', 'Estenda as pernas sem travar os joelhos.', 'Expire ao empurrar.')),
  'hip thrust': four('Hip Thrust', 'hinge', 'Treine primeiro com peso corporal e apoio firme.', 'Hiperestender a lombar e afastar demais os pés.', phase('Posição inicial', 'Escápulas apoiadas, pés firmes e queixo levemente recolhido.', 'Inspire.'), phase('Elevação', 'Empurre pelos calcanhares elevando o quadril.', 'Expire gradualmente.'), phase('Topo', 'Contraia glúteos com costelas controladas.', 'Evite prender o ar.'), phase('Retorno', 'Desça o quadril devagar mantendo controle.', 'Inspire na descida.')),
  'ponte de glúteos': four('Ponte de glúteos', 'hinge', 'Faça sem carga e mantenha os pés próximos o suficiente para sentir glúteos.', 'Arquear a lombar e empurrar só com a ponta dos pés.', phase('Posição inicial', 'Deite, joelhos flexionados e pés inteiros no chão.', 'Inspire.'), phase('Elevação', 'Pressione os pés e eleve o quadril.', 'Expire ao subir.'), phase('Topo', 'Contraia glúteos sem arquear a lombar.', 'Respire curto e controlado.'), phase('Retorno', 'Desça vértebra por vértebra até o chão.', 'Inspire na descida.')),
  'mesa flexora': four('Mesa Flexora', 'curl', 'Ajuste o rolo à altura correta antes de iniciar.', 'Elevar o quadril, usar impulso e encurtar a volta.', phase('Posição inicial', 'Quadril apoiado e joelhos alinhados ao eixo da máquina.', 'Inspire.'), phase('Flexão', 'Leve os calcanhares em direção aos glúteos sem levantar o quadril.', 'Expire ao flexionar.'), phase('Contração', 'Pause brevemente com controle.', 'Respire sem tensão excessiva.'), phase('Retorno', 'Estenda os joelhos lentamente sem bater o peso.', 'Inspire ao voltar.')),
  'elevação de panturrilha em pé': four('Elevação de Panturrilha em Pé', 'calf', 'Use apoio para equilíbrio e comece sem carga.', 'Quicar, deixar tornozelos virarem e descer sem controle.', phase('Posição inicial', 'Pés paralelos e apoio estável.', 'Respire naturalmente.'), phase('Subida', 'Eleve os calcanhares mantendo o peso distribuído.', 'Expire.'), phase('Topo', 'Pause na ponta dos pés sem perder alinhamento.', 'Respiração curta.'), phase('Descida', 'Baixe os calcanhares lentamente.', 'Inspire.')),
  'supino com halteres': four('Supino com Halteres', 'press', 'Use halteres leves e, se possível, peça auxílio para posicioná-los.', 'Cotovelos excessivamente abertos e punhos quebrados.', phase('Posição inicial', 'Escápulas apoiadas, pés firmes e halteres sobre o peito.', 'Inspire.'), phase('Descida', 'Baixe os halteres com cotovelos em trajetória confortável.', 'Mantenha o ar e controle.'), phase('Ponto inferior', 'Pare antes de desconforto no ombro.', 'Tronco estável.'), phase('Empurrar', 'Leve os halteres para cima sem bater um no outro.', 'Expire ao subir.')),
  'remada baixa no cabo': four('Remada Baixa no Cabo', 'pull', 'Use pouca carga até conseguir manter o tronco parado.', 'Balançar o tronco e elevar os ombros.', phase('Posição inicial', 'Tronco alto, braços estendidos e ombros longe das orelhas.', 'Inspire.'), phase('Puxada', 'Conduza cotovelos para trás aproximando as escápulas.', 'Expire ao puxar.'), phase('Contração', 'Pause sem jogar o peito para frente.', 'Respiração controlada.'), phase('Retorno', 'Estenda os braços devagar sem arredondar a coluna.', 'Inspire ao voltar.')),
  'remada com elástico': four('Remada com elástico', 'pull', 'Fixe o elástico em ponto seguro e teste a resistência antes de começar.', 'Dar tranco, elevar ombros e soltar o elástico rapidamente.', phase('Posição inicial', 'Tronco estável e elástico tensionado de leve.', 'Inspire.'), phase('Puxada', 'Puxe cotovelos para trás.', 'Expire.'), phase('Contração', 'Aproxime escápulas sem encolher ombros.', 'Respire.'), phase('Retorno', 'Volte lentamente mantendo tensão.', 'Inspire.')),
  'puxada frontal': four('Puxada Frontal', 'pull', 'Comece leve e escolha pegada confortável.', 'Puxar atrás da cabeça e balançar o tronco.', phase('Posição inicial', 'Peito alto, braços estendidos e ombros baixos.', 'Inspire.'), phase('Puxada', 'Leve a barra à parte superior do peito.', 'Expire.'), phase('Ponto final', 'Cotovelos para baixo sem forçar pescoço.', 'Respire.'), phase('Retorno', 'Suba a barra com controle até estender os braços.', 'Inspire.')),
  'desenvolvimento com halteres': four('Desenvolvimento com Halteres', 'press', 'Faça sentado e com carga leve se ainda estiver aprendendo.', 'Arquear a lombar e elevar os ombros.', phase('Posição inicial', 'Halteres na altura dos ombros e tronco firme.', 'Inspire.'), phase('Subida', 'Empurre acima da cabeça sem perder o alinhamento.', 'Expire.'), phase('Topo', 'Pare antes de travar cotovelos ou elevar ombros.', 'Respire.'), phase('Descida', 'Volte devagar até a posição inicial.', 'Inspire.')),
  'rosca alternada': four('Rosca Alternada', 'curl', 'Use carga que permita manter os cotovelos parados.', 'Balançar o corpo e projetar cotovelos.', phase('Posição inicial', 'Braços ao lado do corpo e punhos neutros.', 'Inspire.'), phase('Flexão', 'Dobre um cotovelo sem mover o ombro.', 'Expire.'), phase('Topo', 'Aperte o bíceps sem dobrar o punho.', 'Respire.'), phase('Retorno', 'Desça lentamente e alterne o lado.', 'Inspire.')),
  'tríceps na corda': four('Tríceps na Corda', 'pushdown', 'Use carga leve e mantenha os cotovelos colados ao corpo.', 'Mover ombros e abrir os cotovelos.', phase('Posição inicial', 'Cotovelos flexionados ao lado do tronco.', 'Inspire.'), phase('Extensão', 'Empurre a corda para baixo estendendo os cotovelos.', 'Expire.'), phase('Final', 'Separe levemente a corda sem jogar os ombros.', 'Respire.'), phase('Retorno', 'Volte devagar até cerca de 90°.', 'Inspire.')),
  'dead bug': four('Dead Bug', 'core-supine', 'Comece movendo só uma perna ou um braço.', 'Arquear a lombar e acelerar.', phase('Posição inicial', 'Deite com quadris/joelhos a 90° e braços para cima.', 'Expire e organize o abdômen.'), phase('Extensão', 'Afaste braço e perna opostos lentamente.', 'Inspire de forma controlada.'), phase('Ponto longo', 'Pare antes de a lombar perder contato confortável.', 'Não prenda o ar.'), phase('Retorno', 'Volte ao centro e alterne lados.', 'Expire ao retornar.')),
  'dead bug controlado': four('Dead Bug controlado', 'core-supine', 'Reduza a amplitude se a lombar arquear.', 'Mover rápido e perder controle do tronco.', phase('Posição inicial', 'Quadris/joelhos a 90° e abdômen organizado.', 'Expire.'), phase('Extensão', 'Alongue membros opostos.', 'Inspire.'), phase('Controle', 'Pare antes de perder a posição lombar.', 'Respire.'), phase('Retorno', 'Volte ao centro e troque o lado.', 'Expire.')),
  'bird dog': four('Bird Dog', 'quadruped', 'Comece elevando apenas um braço ou uma perna.', 'Girar a pelve e hiperestender a lombar.', phase('Posição inicial', 'Quatro apoios, mãos sob ombros e joelhos sob quadris.', 'Inspire.'), phase('Extensão', 'Estenda braço e perna opostos.', 'Expire.'), phase('Sustentação', 'Mantenha quadris paralelos ao chão.', 'Respire.'), phase('Retorno', 'Volte sem deslocar o tronco e alterne.', 'Inspire.')),
  'bicicleta ergométrica': four('Bicicleta Ergométrica', 'bike', 'Ajuste o banco para não pedalar com joelho excessivamente flexionado.', 'Banco baixo demais e resistência excessiva.', phase('Ajuste', 'Regule banco e apoie o meio do pé no pedal.', 'Respire normalmente.'), phase('Cadência', 'Comece leve e encontre ritmo confortável.', 'Respiração contínua.'), phase('Trabalho', 'Mantenha tronco estável e esforço sustentável.', 'Expire sem prender o ar.'), phase('Desaceleração', 'Reduza a carga e a cadência gradualmente.', 'Respiração lenta.')),
  'flexão de braço': four('Flexão de Braço', 'pushup', 'Se necessário, comece inclinada ou com joelhos apoiados.', 'Quadril caindo e cotovelos excessivamente abertos.', phase('Posição inicial', 'Mãos sob/um pouco além dos ombros e corpo alinhado.', 'Inspire.'), phase('Descida', 'Flexione cotovelos e desça o tronco em bloco.', 'Mantenha o abdômen firme.'), phase('Ponto inferior', 'Pare antes de perder alinhamento.', 'Respire controlado.'), phase('Subida', 'Empurre o chão até retornar.', 'Expire.')),
  'flexão': four('Flexão', 'pushup', 'Use joelhos apoiados ou apoio alto se perder a postura.', 'Quadril solto e cotovelos abertos.', phase('Posição inicial', 'Corpo alinhado e mãos firmes.', 'Inspire.'), phase('Descida', 'Desça com controle.', 'Mantenha o tronco firme.'), phase('Ponto inferior', 'Pare antes de perder postura.', 'Respire.'), phase('Subida', 'Empurre o chão.', 'Expire.')),
  'flexão inclinada': four('Flexão inclinada', 'pushup', 'Quanto mais alto o apoio, mais fácil.', 'Apoio instável e quadril caindo.', phase('Posição inicial', 'Mãos em apoio firme e corpo em linha reta.', 'Inspire.'), phase('Descida', 'Leve o peito ao apoio dobrando cotovelos.', 'Controle.'), phase('Ponto inferior', 'Pare sem encostar ou relaxar no apoio.', 'Respire.'), phase('Subida', 'Empurre até estender os braços.', 'Expire.')),
  'flexão diamante com joelhos apoiados': four('Flexão Diamante com Joelhos Apoiados', 'pushup', 'Se punhos/cotovelos incomodarem, use flexão inclinada.', 'Mãos muito à frente e amplitude forçada.', phase('Posição inicial', 'Joelhos no chão, mãos próximas sob o peito.', 'Inspire.'), phase('Descida', 'Dobre os cotovelos mantendo o tronco alinhado.', 'Controle.'), phase('Ponto inferior', 'Pare na amplitude confortável.', 'Respire.'), phase('Subida', 'Empurre o chão com foco no tríceps.', 'Expire.')),
  'flexão diamante': four('Flexão Diamante', 'pushup', 'Domine a flexão convencional antes desta variação.', 'Forçar punhos e abrir cotovelos.', phase('Posição inicial', 'Mãos próximas sob o peito e corpo alinhado.', 'Inspire.'), phase('Descida', 'Desça com cotovelos controlados.', 'Controle.'), phase('Ponto inferior', 'Mantenha postura.', 'Respire.'), phase('Subida', 'Empurre até retornar.', 'Expire.')),
  'polichinelo': four('Polichinelo', 'jumping-jack', 'Use a versão sem salto se impacto ou coordenação forem difíceis.', 'Aterrissagem dura e joelhos para dentro.', phase('Posição inicial', 'Pés juntos e braços ao lado do corpo.', 'Respire.'), phase('Abrir', 'Salte abrindo pernas e elevando braços.', 'Expire.'), phase('Aberto', 'Aterrisse macio com joelhos alinhados.', 'Respire.'), phase('Fechar', 'Retorne pés e braços ao centro.', 'Inspire.')),
  'polichinelo sem salto': four('Polichinelo sem salto', 'jumping-jack', 'Mantenha um pé no chão o tempo todo.', 'Passos largos demais e tronco desorganizado.', phase('Posição inicial', 'Pés juntos e postura alta.', 'Respire.'), phase('Passo lateral', 'Leve um pé para o lado enquanto os braços sobem.', 'Expire.'), phase('Retorno', 'Volte ao centro com controle.', 'Inspire.'), phase('Outro lado', 'Repita para o outro lado.', 'Respiração contínua.')),
  'mergulho no banco': four('Mergulho no Banco', 'dip', 'Use banco firme e amplitude pequena no início.', 'Ombros muito à frente e apoio instável.', phase('Posição inicial', 'Mãos no banco, quadril próximo ao apoio e pés firmes.', 'Inspire.'), phase('Descida', 'Dobre cotovelos sem deixar ombros subirem.', 'Controle.'), phase('Ponto inferior', 'Pare na amplitude confortável.', 'Respire.'), phase('Subida', 'Estenda cotovelos mantendo o corpo perto do banco.', 'Expire.')),
  'corrida estacionária com joelhos altos': four('Joelhos Altos', 'high-knees', 'Use marcha rápida sem salto se necessário.', 'Inclinar demais o tronco e bater os pés.', phase('Posição inicial', 'Postura alta e abdômen ativo.', 'Respire.'), phase('Joelho direito', 'Eleve um joelho até altura confortável.', 'Expire curto.'), phase('Troca', 'Pouse macio e alterne as pernas.', 'Respiração contínua.'), phase('Ritmo', 'Mantenha cadência sem perder postura.', 'Respire ritmado.')),
  'joelhos altos': four('Joelhos Altos', 'high-knees', 'Marcha rápida é uma alternativa válida.', 'Impacto excessivo e tronco inclinado.', phase('Posição inicial', 'Postura alta.', 'Respire.'), phase('Elevação', 'Eleve um joelho.', 'Expire.'), phase('Troca', 'Pouse macio e alterne.', 'Respire.'), phase('Ritmo', 'Mantenha ritmo confortável.', 'Respiração contínua.')),
  'marcha com joelhos elevados': four('Marcha com Joelhos Elevados', 'high-knees', 'Use apoio se o equilíbrio estiver inseguro.', 'Inclinar o tronco e acelerar demais.', phase('Posição inicial', 'Fique alto, pés firmes.', 'Respire.'), phase('Elevar', 'Eleve um joelho sem inclinar o corpo.', 'Expire.'), phase('Retorno', 'Apoie o pé com controle.', 'Inspire.'), phase('Alternar', 'Repita do outro lado.', 'Respiração contínua.')),
  'prancha inclinada': four('Prancha inclinada', 'pushup', 'Use parede ou banco firme; quanto mais alto, mais fácil.', 'Quadril caindo e ombros encolhidos.', phase('Posição inicial', 'Antebraços ou mãos no apoio e corpo alinhado.', 'Expire e ative o abdômen.'), phase('Estabilizar', 'Empurre o apoio e mantenha ombros organizados.', 'Respire normalmente.'), phase('Sustentar', 'Mantenha quadril alinhado sem prender o ar.', 'Respiração contínua.'), phase('Finalizar', 'Saia da posição devagar e fique em pé.', 'Respire fundo.')),
  'tai chi — despertar do qi': four('Tai Chi — Despertar do Qi', 'tai-chi', 'Use postura alta e movimentos pequenos no início.', 'Elevar ombros e prender a respiração.', phase('Base', 'Pés na largura dos ombros e joelhos soltos.', 'Inspire.'), phase('Elevar braços', 'Suba os braços suavemente até o peito.', 'Continue inspirando.'), phase('Acomodar', 'Flexione levemente os joelhos sem dor.', 'Comece a expirar.'), phase('Descer braços', 'Baixe os braços e volte à base.', 'Expire lentamente.')),
  'despertar do qi': four('Despertar do Qi', 'tai-chi', 'Movimentos lentos e postura confortável.', 'Pressa e tensão nos ombros.', phase('Base', 'Pés estáveis.', 'Inspire.'), phase('Elevar', 'Suba os braços.', 'Inspire.'), phase('Flexionar', 'Flexione levemente joelhos.', 'Expire.'), phase('Retornar', 'Baixe os braços.', 'Expire.')),
  'tai chi — mover as mãos como nuvens': four('Tai Chi — Mãos como Nuvens', 'tai-chi', 'Faça a transferência de peso pequena até ganhar segurança.', 'Torcer joelhos e mover só os braços.', phase('Base', 'Pés afastados e joelhos soltos.', 'Inspire.'), phase('Transferir', 'Leve o peso para um lado enquanto as mãos circulam.', 'Expire.'), phase('Centro', 'Passe pelo centro mantendo joelhos alinhados.', 'Inspire.'), phase('Outro lado', 'Transfira para o lado oposto.', 'Expire.')),
  'mãos como nuvens': four('Mãos como Nuvens', 'tai-chi', 'Mantenha o movimento pequeno e contínuo.', 'Torcer joelhos e acelerar.', phase('Base', 'Pés afastados.', 'Inspire.'), phase('Lado 1', 'Transfira peso e circule mãos.', 'Expire.'), phase('Centro', 'Volte pelo centro.', 'Inspire.'), phase('Lado 2', 'Repita para o outro lado.', 'Expire.')),
  'tai chi — repelir o macaco': four('Tai Chi — Repelir o Macaco', 'walk', 'Passos curtos e apoio próximo se necessário.', 'Passo longo e rotação brusca.', phase('Base', 'Postura confortável.', 'Inspire.'), phase('Passo atrás', 'Leve um pé para trás com controle.', 'Expire.'), phase('Empurrar', 'Uma mão avança enquanto a outra recolhe.', 'Respire.'), phase('Alternar', 'Retorne e repita do outro lado.', 'Respiração contínua.')),
  'repelir o macaco': four('Repelir o Macaco', 'walk', 'Faça passos curtos.', 'Rotação brusca e perda de equilíbrio.', phase('Base', 'Postura estável.', 'Inspire.'), phase('Passo atrás', 'Pé para trás.', 'Expire.'), phase('Empurrar', 'Coordene as mãos.', 'Respire.'), phase('Alternar', 'Troque o lado.', 'Respire.')),
  'tai chi — abraçar a árvore': four('Tai Chi — Abraçar a Árvore', 'tai-chi', 'Joelhos só levemente flexionados.', 'Tensão nas mãos e ombros.', phase('Base', 'Pés estáveis e joelhos soltos.', 'Inspire.'), phase('Arcos', 'Forme um círculo com os braços à frente.', 'Expire.'), phase('Sustentar', 'Relaxe ombros e mantenha postura.', 'Respire lentamente.'), phase('Fechar', 'Baixe os braços e estenda suavemente as pernas.', 'Expire.')),
  'abraçar a árvore': four('Abraçar a Árvore', 'tai-chi', 'Postura confortável.', 'Ombros tensos e joelhos muito flexionados.', phase('Base', 'Pés firmes.', 'Inspire.'), phase('Abraçar', 'Braços arredondados.', 'Expire.'), phase('Sustentar', 'Relaxe.', 'Respire.'), phase('Fechar', 'Baixe braços.', 'Expire.')),
  'tai chi — transferência de peso e equilíbrio': four('Transferência de Peso e Equilíbrio', 'walk', 'Use parede ou cadeira firme como apoio.', 'Transferir peso rápido e travar joelhos.', phase('Base', 'Pés confortavelmente afastados.', 'Inspire.'), phase('Lado 1', 'Transfira peso devagar para uma perna.', 'Expire.'), phase('Centro', 'Retorne ao centro com controle.', 'Inspire.'), phase('Lado 2', 'Transfira para a outra perna.', 'Expire.')),
  'transferência de peso': four('Transferência de Peso', 'walk', 'Apoio próximo ajuda iniciantes.', 'Pressa e joelhos travados.', phase('Base', 'Pés estáveis.', 'Inspire.'), phase('Lado 1', 'Transfira peso.', 'Expire.'), phase('Centro', 'Retorne.', 'Inspire.'), phase('Lado 2', 'Transfira para o outro lado.', 'Expire.')),
  'tai chi walking — passos à frente': four('Tai Chi Walking — Passos à Frente', 'walk', 'Dê passos curtos e só transfira o peso depois que o pé estiver estável.', 'Passo longo e joelho para dentro.', phase('Preparar', 'Peso na perna de trás e pé da frente leve.', 'Inspire.'), phase('Calcanhar', 'Toque o calcanhar à frente.', 'Expire.'), phase('Transferir', 'Passe o peso gradualmente para o pé da frente.', 'Respire.'), phase('Reunir', 'Traga o pé de trás e prepare o próximo passo.', 'Inspire.')),
  'passos à frente': four('Passos à Frente', 'walk', 'Passos pequenos.', 'Transferência brusca.', phase('Preparar', 'Peso estável.', 'Inspire.'), phase('Calcanhar', 'Toque à frente.', 'Expire.'), phase('Transferir', 'Leve o peso.', 'Respire.'), phase('Reunir', 'Aproxime o outro pé.', 'Inspire.')),
  'tai chi walking — passos para trás': four('Tai Chi Walking — Passos para Trás', 'walk', 'Confira o espaço e use apoio firme.', 'Passos grandes e cruzar as pernas.', phase('Preparar', 'Olhar à frente e espaço livre atrás.', 'Inspire.'), phase('Ponta do pé', 'Leve um pé para trás tocando a ponta.', 'Expire.'), phase('Transferir', 'Passe o peso devagar para trás.', 'Respire.'), phase('Reunir', 'Ajuste o pé da frente e repita.', 'Inspire.')),
  'passos para trás': four('Passos para Trás', 'walk', 'Use apoio e passos curtos.', 'Passo grande e falta de atenção ao espaço.', phase('Preparar', 'Espaço livre.', 'Inspire.'), phase('Tocar atrás', 'Ponta do pé atrás.', 'Expire.'), phase('Transferir', 'Peso gradual.', 'Respire.'), phase('Reunir', 'Ajuste.', 'Inspire.')),
  'tai chi chen — postura do arco': four('Tai Chi Chen — Postura do Arco', 'lunge', 'Use base curta e postura alta no início.', 'Joelho para dentro e base baixa demais.', phase('Base', 'Dê um passo confortável à frente.', 'Inspire.'), phase('Transferir', 'Flexione o joelho dianteiro dentro do conforto.', 'Expire.'), phase('Sustentar', 'Mantenha tronco alto e joelhos alinhados.', 'Respire continuamente.'), phase('Sair', 'Transfira o peso para trás e reduza a postura.', 'Inspire.')),
  'postura do arco': four('Postura do Arco', 'lunge', 'Base curta para iniciantes.', 'Flexão profunda dolorosa.', phase('Base', 'Passo confortável.', 'Inspire.'), phase('Flexionar', 'Joelho dianteiro flexiona.', 'Expire.'), phase('Sustentar', 'Alinhamento.', 'Respire.'), phase('Retornar', 'Peso para trás.', 'Inspire.')),
  'tai chi chen — empurrar na postura do arco': four('Tai Chi Chen — Empurrar', 'lunge', 'Aprenda a postura do arco antes de adicionar os braços.', 'Empurrar rápido e rodar o joelho.', phase('Base', 'Assuma postura do arco confortável.', 'Inspire.'), phase('Empurrar', 'Mãos avançam enquanto o peso vai levemente à frente.', 'Expire.'), phase('Final', 'Pare sem travar cotovelos.', 'Respire.'), phase('Recolher', 'Mãos e peso retornam com controle.', 'Inspire.')),
  'empurrar controlado': four('Empurrar controlado', 'lunge', 'Movimento lento.', 'Impulso e ombros tensos.', phase('Base', 'Postura confortável.', 'Inspire.'), phase('Empurrar', 'Mãos à frente.', 'Expire.'), phase('Final', 'Pare com controle.', 'Respire.'), phase('Recolher', 'Volte.', 'Inspire.')),
  'tai chi yang — aparar a cauda do pássaro': four('Tai Chi Yang — Aparar a Cauda do Pássaro', 'tai-chi', 'Aprenda em partes antes de tentar fluxo contínuo.', 'Rotação lombar forçada e pressa.', phase('Preparar', 'Base confortável e braços arredondados.', 'Inspire.'), phase('Expandir', 'Transfira peso e expanda os braços suavemente.', 'Expire.'), phase('Recolher', 'Traga braços e peso de volta sem colapsar postura.', 'Inspire.'), phase('Conectar', 'Passe ao próximo lado mantendo movimento fluido.', 'Expire.')),
  'aparar a cauda do pássaro': four('Aparar a Cauda do Pássaro', 'tai-chi', 'Faça devagar e em partes.', 'Forçar rotação.', phase('Preparar', 'Base confortável.', 'Inspire.'), phase('Expandir', 'Braços e peso avançam.', 'Expire.'), phase('Recolher', 'Volte.', 'Inspire.'), phase('Conectar', 'Continue fluido.', 'Expire.')),
  'caminhada contínua': four('Caminhada Contínua', 'walk', 'Passos curtos e ritmo estável.', 'Acelerar e perder o controle.', phase('Preparar', 'Postura alta.', 'Inspire.'), phase('Passo', 'Toque o pé com controle.', 'Expire.'), phase('Transferir', 'Passe o peso gradualmente.', 'Respire.'), phase('Continuar', 'Repita mantendo fluidez.', 'Respiração contínua.')),
  'sustentação isométrica': four('Sustentação Isométrica', 'lunge', 'Use postura alta e reduza o tempo se a técnica cair.', 'Prender a respiração e baixar demais.', phase('Entrar', 'Assuma a postura de forma gradual.', 'Inspire.'), phase('Ajustar', 'Alinhe joelhos, quadris e tronco.', 'Expire.'), phase('Sustentar', 'Mantenha tensão moderada sem dor.', 'Respire continuamente.'), phase('Sair', 'Reduza a flexão e volte à base.', 'Expire.')),
  'retorno consciente': four('Retorno Consciente', 'tai-chi', 'Use este bloco para desacelerar.', 'Movimentos bruscos e prender o ar.', phase('Base', 'Postura confortável.', 'Inspire.'), phase('Soltar', 'Relaxe braços e ombros.', 'Expire.'), phase('Respirar', 'Faça respirações lentas e naturais.', 'Respire.'), phase('Fechar', 'Volte à postura neutra.', 'Expire.')),
  'movimentos circulares': four('Movimentos Circulares', 'tai-chi', 'Círculos pequenos no início.', 'Forçar ombros e coluna.', phase('Base', 'Pés estáveis.', 'Inspire.'), phase('Circular', 'Desenhe círculos suaves com os braços.', 'Expire.'), phase('Transferir', 'Associe pequena transferência de peso.', 'Respire.'), phase('Retornar', 'Volte ao centro.', 'Inspire.')),
  'fechamento': four('Fechamento', 'tai-chi', 'Use o bloco para desacelerar.', 'Prender a respiração.', phase('Base', 'Postura neutra.', 'Inspire.'), phase('Elevar', 'Eleve braços suavemente.', 'Inspire.'), phase('Descer', 'Baixe os braços relaxando ombros.', 'Expire.'), phase('Final', 'Permaneça alguns segundos em postura confortável.', 'Respire naturalmente.')),
};

function normalize(value: string) {
  return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLocaleLowerCase('pt-BR').trim();
}

const normalizedCatalog = new Map(Object.entries(catalog).map(([name, guidance]) => [normalize(name), guidance]));

export function getExerciseGuidance(name: string): ExerciseGuidance {
  const exact = normalizedCatalog.get(normalize(name));
  if (exact) return exact;
  return four(
    name,
    'tai-chi',
    'Comece devagar, com amplitude confortável, e priorize controle antes de velocidade ou carga.',
    'Evite compensações, movimentos bruscos e qualquer repetição com dor.',
    phase('Posição inicial', 'Organize a postura e confira apoio/equipamento.', 'Inspire e prepare o movimento.'),
    phase('Movimento', 'Execute a fase principal lentamente e com controle.', 'Expire durante o maior esforço.'),
    phase('Ponto final', 'Pare antes de perder alinhamento ou conforto.', 'Mantenha a respiração fluida.'),
    phase('Retorno', 'Volte à posição inicial sem soltar a carga ou o corpo de forma brusca.', 'Inspire durante o retorno.'),
  );
}

export function guidanceUrl(name: string) {
  return `evolua-guide://${encodeURIComponent(name)}`;
}
